const mongoose = require("mongoose");

const userResumeSchema = mongoose.Schema({
  userFirstName: String,
  userSecondName: String,
  userGender: String,
  userAge: String,
  userProfession: String,
  userLocation: String,
  userPhoneNumber: String,
  userEmail: String,
  userHouseAddress: String,
  userProfileDescription: String,
  userFirstProfileWebsite: String,
  userGitHubProfileName: String,
  userSecondProfileWebsite: String,
  userLinkedInProfileName: String,
  userThirdProfileWebsite: String,
  userPersonalWebsiteLink: String,
  userHighSchoolDegreeName: String,
  userHighSchoolName: String,
  userHighSchoolStartingDate: String,
  userHighSchoolEndingDate: String,
  userHighSchoolExperience: String,
  userCollegeDegreeName: String,
  userCollegeName: String,
  userCollegeStartingDate: String,
  userCollegeEndingDate: String,
  userCollegeExperience: String,
  userBachelorDegreeName: String,
  userUniversityName: String,
  userBachelorStartingDate: String,
  userBachelorEndingDate: String,
  userUniversityExperience: String,
  user1stExperience: String,
  user1stCompanyName: String,
  user1stExperienceStartingDate: String,
  user1stExperienceEndingDate: String,
  user1stCompanyExperience: String,
  user2ndExperience: String,
  user2ndCompanyName: String,
  user2ndExperienceStartingDate: String,
  user2ndExperienceEndingDate: String,
  user2ndCompanyExperience: String,
  user3rdExperience: String,
  user3rdCompanyName: String,
  user3rdExperienceStartingDate: String,
  user3rdExperienceEndingDate: String,
  user3rdCompanyExperience: String,
  userSkills: String,
});

const UserResumeSchema = mongoose.model("UserResumeData", userResumeSchema);

module.exports = UserResumeSchema;
